project:
  title: "animint2 Contributions via GSOC"
  author: J. Chen

format:
  html:
    css: changes.css
from: markdown+emoji

title: "animint2 GSOC Examination"
author: J. Chen
format: 
  html:
    css: changes.css
mainfont: "Roboto Condensed"
monofont: "Roboto Mono"
number-sections: FALSE
toc: TRUE
toc-location: left
toc-title: "Contents:"
linkcolor: "#043521"
reference-location: margin
cap-location: margin
website:
  cookie-consent: express

